"""fix_user_symbols_id_autoincrement

Revision ID: a5d363a74f27
Revises: e6a55eadc79f
Create Date: 2025-09-29 09:41:05.039114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d363a74f27'
down_revision: Union[str, Sequence[str], None] = 'e6a55eadc79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
